# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

commands:
    create_concatenated_package_lock:
    description: "Concatenate all package-lock.json files recognized by lerna.js into single file. File is used as checksum source for part of caching key."
parameters:
  filename:
      type: string
  steps:
    - run:
      name: Combine package-lock.json files to single file
      command: npx lerna list -p -a | awk -F packages '{printf "\"packages%s/package-lock.json\" ", $2}' | xargs cat > << parameters.filename >>
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.6

    working_directory: ~/node-go

    steps:
      - checkout
      # - run: sudo apt-get install postgresql-client-11.4
      # - run: pg_ctl -D /var/lib/postgresql/data -l logfile start
      # - run: psql CREATE DATABASE circle_test

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            

      - run: npm install
      - run: npm run bootstrap

      - save_cache:
          paths:
            - node_modules
          key: 
            v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm install react
      - run: npm install react-dom
      
      # ! temporary fix for deprecated package: minimist
      - run: npm audit --audit-level=moderate
      
      # DEPLOY
      - run: git subtree push --prefix packages/server https://heroku:$HEROKU_API_KEY@git.heroku.com/$HK_API.git master
      - run: git subtree push --prefix packages/play-node-go https://heroku:$HEROKU_API_KEY@git.heroku.com/$HK_PLAY.git master